import React from "react";
import Head from "next/head";
import marvelApi from "../../api/marvelApi";
import Detail from "../../components/Characters/Detail/Detail";

export default function CharacterDetail({ character, comics }) {
  return (
    <>
      <Head>
        <title>Marvel Character Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Detail character={character}
                comics={comics}
        />
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  let character = {};
  let comics = {};
  const { query } = context;

  try {
    character = await marvelApi.getCharacterById(query.id);
    character = character.data.results[0];

    comics = await marvelApi.getComicsByCharacter(query.id);
    comics = comics.data.results;

  } catch(error) {
    console.log(error);
  }

  return {
    props: {
      character,
      comics,
    },
  };
};
