import md5 from "md5";
import Head from "next/head";
import getConfig from "next/config";
import List from "../components/Characters/List/List";

export default function Home({ characters }) {
  return (
    <>
      <Head>
        <title>Marvel Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <List characters={characters} />
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  let characters = {};
  const { publicRuntimeConfig } = getConfig();

  try {
    let hash = md5(publicRuntimeConfig.TIMESTAMP + publicRuntimeConfig.MARVEL_PRIVATE_KEY + publicRuntimeConfig.MARVEL_PUBLIC_KEY);

    characters = await fetch(`https://gateway.marvel.com/v1/public/characters?ts=${publicRuntimeConfig.TIMESTAMP}&apikey=${publicRuntimeConfig.MARVEL_PUBLIC_KEY}&hash=${hash}&limit=30`);
    characters = await characters.json();
    characters = characters.data;

  } catch(error) {
    console.log(error);
  }

  return {
    props: {
      characters
    },
  };
};
